.TH "ENGLISH KABBALAH" 1 "July 2013" "eng-qbl 0.3" "English Kabbalah"
.SH NAME
The English Kabbalah suite
.SH SYNOPSIS
.B eng-qbl
[command] [options]
.SH DESCRIPTION
\fBeng-qbl\fR can be used to perform any of the functions of the
other applications in the suite. \fBcommand\fR is the name of the
application while \fBoptions\fR are the application's own command
options.
.PP
If no command is given, \fBeng-qbl\fR is interactive mode.
.SH EXAMPLES
.SS Command-line Mode
\fBeng-qbl\fR gematria -s Genesis.txt Eden
.PP
.SS Interactive Mode
eng-qbl> loadfile
.br
loadfile> Genesis.txt
.br
loadfile> File "Genesis.txt" loaded.
.br
eng-qbl> gematria
.br
gematria> Eden -s
.PP
.br
---- Gematria Results --------------------------------
.br
168
.br
---- Search Results ----------------------------------
.br
is, man, air, Eden, Madai, Dedan, flee, feel, Edar, balm, bank, Ohad, Belah
.br
------------------------------------------------------
.SH AUTHOR
Written by Marc Sylvestre <marc.sylvestre@manhydra.com>
.SH SEE ALSO
.IR english-kabbalah (1),
.IR gematria (1),
.IR temurah (1),
.IR notarikon (1)
.IR anagram (1)
